#!/usr/bin/env bash
# spawn.sh — scaffold a cross-session coordination bus for a Claude Code project.
#
# Creates ~/.claude/<project>-coord/ with:
#   - cli.py            (parameterized from cli.py.template)
#   - <agent>.sh        (one wrapper per agent, sets CLAUDE_AGENT_ID)
#   - human.sh          (human override wrapper)
#   - inbox.jsonl       (empty, ready for first message)
#
# Prints the Monitor command each session should run to receive its messages.
#
# USAGE:
#   ~/.claude/coord-template/spawn.sh <project-slug> <agent1> <agent2> [agent3] ...
#
# EXAMPLES:
#   spawn.sh myproject coder reviewer
#   spawn.sh webapp backend frontend reviewer
#   spawn.sh research scout skeptic synthesizer architect

set -euo pipefail

if [ $# -lt 3 ]; then
  echo "usage: spawn.sh <project-slug> <agent-id-1> <agent-id-2> [agent-id-3] ..."
  echo ""
  echo "  project-slug : short name, lowercase + hyphens. Used in the dir name."
  echo "                 dir created at ~/.claude/<project-slug>-coord/"
  echo ""
  echo "  agent-id-N   : 2 or more session identifiers. Lowercase, no spaces."
  echo "                 Each gets a wrapper script <agent>.sh that stamps"
  echo "                 CLAUDE_AGENT_ID for the cli.py."
  exit 1
fi

PROJECT="$1"
shift
AGENTS=("$@")

if [ ${#AGENTS[@]} -lt 2 ]; then
  echo "ERROR: need at least 2 agent IDs."
  exit 1
fi

TEMPLATE_DIR="$HOME/.claude/coord-template"
DEST_DIR="$HOME/.claude/${PROJECT}-coord"

if [ -d "$DEST_DIR" ]; then
  echo "ERROR: $DEST_DIR already exists. Delete it first or pick a different project slug."
  exit 1
fi

if [ ! -f "$TEMPLATE_DIR/cli.py.template" ]; then
  echo "ERROR: template missing at $TEMPLATE_DIR/cli.py.template"
  exit 1
fi

mkdir -p "$DEST_DIR"

# Build the Python set literal: {"agent1", "agent2", ...}
PY_SET="{"
SHELL_LIST=""
for i in "${!AGENTS[@]}"; do
  if [ "$i" -gt 0 ]; then
    PY_SET="$PY_SET, "
    SHELL_LIST="$SHELL_LIST, "
  fi
  PY_SET="$PY_SET\"${AGENTS[$i]}\""
  SHELL_LIST="$SHELL_LIST${AGENTS[$i]}"
done
PY_SET="$PY_SET}"

# Generate cli.py from template using sed substitutions.
# Use | as sed delimiter to avoid escaping forward slashes.
sed \
  -e "s|__PROJECT_NAME__|${PROJECT}|g" \
  -e "s|__AGENTS_LIST__|${SHELL_LIST}|g" \
  -e "s|__AGENTS_PYTHON_SET__|${PY_SET}|g" \
  "$TEMPLATE_DIR/cli.py.template" \
  > "$DEST_DIR/cli.py"
chmod +x "$DEST_DIR/cli.py"

# Generate per-agent wrapper scripts.
for agent in "${AGENTS[@]}"; do
  cat > "$DEST_DIR/${agent}.sh" <<EOF
#!/usr/bin/env bash
# ${agent}.sh — generated by ~/.claude/coord-template/spawn.sh
# Sets CLAUDE_AGENT_ID=${agent} and delegates to cli.py.
set -e
SCRIPT_DIR="\$(cd "\$(dirname "\$0")" && pwd)"
export CLAUDE_AGENT_ID=${agent}
export PYTHONIOENCODING=utf-8
exec python "\$SCRIPT_DIR/cli.py" "\$@"
EOF
  chmod +x "$DEST_DIR/${agent}.sh"
done

# Generate human.sh (human override).
cat > "$DEST_DIR/human.sh" <<'EOF'
#!/usr/bin/env bash
# human.sh — human override wrapper. Auto-tags sender_kind="human".
set -e
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
export CLAUDE_AGENT_ID=human
export PYTHONIOENCODING=utf-8
exec python "$SCRIPT_DIR/cli.py" "$@"
EOF
chmod +x "$DEST_DIR/human.sh"

# Empty inbox.
touch "$DEST_DIR/inbox.jsonl"

# Pretty output.
echo "✓ Bus scaffolded at $DEST_DIR"
echo ""
echo "Files created:"
ls -la "$DEST_DIR"
echo ""
echo "─── Each session should run ONE Monitor watcher when it starts ───"
echo ""
for agent in "${AGENTS[@]}"; do
  cat <<EOF
For session '${agent}':
  Monitor command (paste in that Claude Code window):
    tail -F -n +1 $DEST_DIR/inbox.jsonl | grep --line-buffered -E '"to": ?"(${agent}|all)"' | grep --line-buffered -vE '"from": ?"${agent}"'

  Send a message:
    $DEST_DIR/${agent}.sh send <recipient> "your message" --thread <thread-name>

  Read inbox:
    $DEST_DIR/${agent}.sh inbox ${agent}

EOF
done

cat <<EOF
─── Human override ───

  $DEST_DIR/human.sh send all "course correction" --human

─── Done ───

EOF
